# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('winner', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
